import { Request, Response } from 'express';
import * as mediaService from '../services/mediaService';
import * as systemSettingsService from '../services/systemSettingsService';
import fs from 'fs';
import path from 'path';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';

interface StorageSettings {
    provider: string;
    bucket?: string;
    region?: string;
    accessKeyId?: string;
    secretAccessKey?: string;
    endpoint?: string;
}

export const uploadFiles = async (req: Request, res: Response) => {
  try {
    const { tenantId } = (req as any).user;

    if (!req.files || (req.files as Express.Multer.File[]).length === 0) {
      console.error('No files uploaded');
      return res.status(400).json({ message: 'No files uploaded' });
    }

    // Get System Settings to check storage provider
    const systemSettings = await systemSettingsService.getSystemSettings();
    const settings = systemSettings?.storage as unknown as StorageSettings | undefined;
    const isS3 = settings?.provider === 's3';

    let s3Client: S3Client | null = null;
    if (isS3 && settings) {
        s3Client = new S3Client({
            region: settings.region,
            credentials: {
                accessKeyId: settings.accessKeyId || '',
                secretAccessKey: settings.secretAccessKey || '',
            },
            endpoint: settings.endpoint || undefined,
            forcePathStyle: !!settings.endpoint, // Needed for MinIO/DigitalOcean
        });
    }

    const uploadedFiles = [];
    const files = req.files as Express.Multer.File[];


    // Parse metadata if present
    let metadataMap: Record<string, any> = {};
    if (req.body.metadata) {
      try {
        const metadataList = JSON.parse(req.body.metadata);
        if (Array.isArray(metadataList)) {
            metadataList.forEach((m: any) => {
                if (m && m.name) {
                    metadataMap[m.name] = m;
                }
            });
        }
      } catch (e) {
        console.error("Failed to parse metadata", e);
      }
    }

    for (const file of files) {
      let url = '';
      
      if (isS3 && s3Client && settings?.bucket) {
          // Upload to S3
          const fileStream = fs.createReadStream(file.path);
          
          // Use the same relative path structure as local storage
          const relativePath = (req as any).fileRelativePath || `${tenantId}/${new Date().getFullYear()}/${(new Date().getMonth()+1).toString().padStart(2, '0')}/${new Date().getDate().toString().padStart(2, '0')}`;
          
          // Use the unique filename generated by Multer to avoid collisions
          const key = `uploads/${relativePath}/${file.filename}`;
          
          try {
              const upload = new Upload({
                  client: s3Client,
                  params: {
                      Bucket: settings.bucket,
                      Key: key,
                      Body: fileStream,
                      ContentType: file.mimetype,
                  },
              });

              await upload.done();
              
              // Construct S3 URL
              if (settings.endpoint) {
                   url = `${settings.endpoint}/${settings.bucket}/${key}`;
              } else {
                   url = `https://${settings.bucket}.s3.${settings.region}.amazonaws.com/${key}`;
              }

              // Remove local file
              fs.unlinkSync(file.path);
          } catch (err) {
              console.error('S3 Upload Error:', err);
              throw new Error('Failed to upload to S3');
          }
      } else {
          // Local Storage
          // Calculate relative path from the actual file location to ensure consistency
          const uploadDir = path.join(__dirname, '../../uploads');
          const relativePath = path.relative(uploadDir, file.destination).split(path.sep).join('/');
          
          // Ensure relativePath doesn't start with / if it's empty
          const prefix = relativePath && relativePath !== '.' ? `${relativePath}/` : '';
          
          url = `/uploads/${prefix}${file.filename}`;
      }
      
      const meta = metadataMap[file.originalname] || {};

      const fileData = {
        name: file.originalname,
        size: file.size,
        mimeType: file.mimetype,
        url: url,
        folderId: req.body.folderId || undefined,
        width: meta.width,
        height: meta.height,
        duration: meta.duration
      };

      const savedFile = await mediaService.createFile(tenantId, fileData);
      uploadedFiles.push(savedFile);
    }

    res.status(201).json(uploadedFiles);
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const createFolder = async (req: Request, res: Response) => {
  try {
    const { tenantId } = (req as any).user;
    const folder = await mediaService.createFolder(tenantId, req.body);
    res.status(201).json(folder);
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const getAllFolders = async (req: Request, res: Response) => {
  try {
    const { tenantId } = (req as any).user;
    const folders = await mediaService.getFolders(tenantId);
    res.json(folders);
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
};

export const getLibrary = async (req: Request, res: Response) => {
  try {
    const { tenantId } = (req as any).user;
    const { folderId, search } = req.query;
    
    const files = await mediaService.getFiles(tenantId, folderId as string, search as string);
    const allFolders = await mediaService.getFolders(tenantId); 
    
    const targetFolderId = (folderId as string) || null;
    const currentFolders = allFolders.filter(f => f.parentId === targetFolderId);

    res.json({ folders: currentFolders, files });
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
};

export const updateFile = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { tenantId } = (req as any).user;
    const file = await mediaService.updateFile(id, tenantId, req.body);
    res.json(file);
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const deleteFile = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { tenantId } = (req as any).user;
    await mediaService.deleteFile(id, tenantId);
    res.json({ message: 'File deleted' });
  } catch (error: any) {
    if (error.code === 'MEDIA_IN_USE') {
        return res.status(409).json({ 
            message: 'File is in use and cannot be deleted', 
            code: 'MEDIA_IN_USE',
            playlists: error.playlists 
        });
    }
    res.status(400).json({ message: error.message });
  }
};

export const updateFolder = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { tenantId } = (req as any).user;
    const folder = await mediaService.updateFolder(id, tenantId, req.body);
    res.json(folder);
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const deleteFolder = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { tenantId } = (req as any).user;
    await mediaService.deleteFolder(id, tenantId);
    res.status(200).json({ message: 'Folder deleted' });
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const bulkDelete = async (req: Request, res: Response) => {
  try {
    const { fileIds = [], folderIds = [] } = req.body;
    const { tenantId } = (req as any).user;
    
    const result = await mediaService.bulkDelete(tenantId, fileIds, folderIds);
    res.status(200).json({ message: 'Operation completed', result });
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const bulkMove = async (req: Request, res: Response) => {
  try {
    const { fileIds = [], folderIds = [], targetFolderId } = req.body;
    const { tenantId } = (req as any).user;
    
    await mediaService.bulkMove(tenantId, fileIds, folderIds, targetFolderId);
    res.status(200).json({ message: 'Items moved' });
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};
