import { Request, Response } from 'express';
import * as mediaService from '../services/mediaService';
import * as systemSettingsService from '../services/systemSettingsService';
import crypto from 'crypto';
import fs from 'fs';
import http from 'http';
import https from 'https';
import path from 'path';
import { S3Client, PutObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';

import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

interface CdnSettings {
    enabled: boolean;
    baseUrl: string;
}

interface StorageSettings {
    provider: string;
    bucket?: string;
    region?: string;
    accessKeyId?: string;
    secretAccessKey?: string;
    endpoint?: string;
}

export const uploadFiles = async (req: Request, res: Response) => {
  try {
    const { tenantId } = (req as any).user;

    if (!req.files || (req.files as Express.Multer.File[]).length === 0) {
      console.error('No files uploaded');
      return res.status(400).json({ message: 'No files uploaded' });
    }

    // Get System Settings to check storage provider
    const systemSettings = await systemSettingsService.getSystemSettings();
    const settings = systemSettings?.storage as unknown as StorageSettings | undefined;
    const cdnSettings = systemSettings?.cdn as unknown as CdnSettings | undefined;
    const isS3 = settings?.provider === 's3';

    let s3Client: S3Client | null = null;
    if (isS3 && settings) {
        s3Client = new S3Client({
            region: settings.region,
            credentials: {
                accessKeyId: settings.accessKeyId || '',
                secretAccessKey: settings.secretAccessKey || '',
            },
            endpoint: settings.endpoint || undefined,
            forcePathStyle: !!settings.endpoint, // Needed for MinIO/DigitalOcean
        });
    }

    const uploadedFiles = [];
    const files = req.files as Express.Multer.File[];


    // Parse metadata if present
    let metadataMap: Record<string, any> = {};
    if (req.body.metadata) {
      try {
        const metadataList = JSON.parse(req.body.metadata);
        if (Array.isArray(metadataList)) {
            metadataList.forEach((m: any) => {
                if (m && m.name) {
                    metadataMap[m.name] = m;
                }
            });
        }
      } catch (e) {
        console.error("Failed to parse metadata", e);
      }
    }

    for (const file of files) {
      let url = '';
      const sha256 = await computeSha256FromFile(file.path);
      
      if (isS3 && s3Client && settings?.bucket) {
          // Upload to S3
          const fileStream = fs.createReadStream(file.path);
          
          // Use the same relative path structure as local storage
          const relativePath = (req as any).fileRelativePath || `${tenantId}/${new Date().getFullYear()}/${(new Date().getMonth()+1).toString().padStart(2, '0')}/${new Date().getDate().toString().padStart(2, '0')}`;
          
          // Use the unique filename generated by Multer to avoid collisions
          const key = `uploads/${relativePath}/${file.filename}`;
          
          try {
              const upload = new Upload({
                  client: s3Client,
                  params: {
                      Bucket: settings.bucket,
                      Key: key,
                      Body: fileStream,
                      ContentType: file.mimetype,
                  },
              });

              await upload.done();
              
              // Construct S3 URL
              if (cdnSettings?.enabled && cdnSettings?.baseUrl) {
                  const baseUrl = cdnSettings.baseUrl.replace(/\/$/, '');
                  url = `${baseUrl}/${key}`;
              } else if (settings.endpoint) {
                   url = `${settings.endpoint}/${settings.bucket}/${key}`;
              } else {
                   url = `https://${settings.bucket}.s3.${settings.region}.amazonaws.com/${key}`;
              }

              // Remove local file
              fs.unlinkSync(file.path);
          } catch (err) {
              console.error('S3 Upload Error:', err);
              throw new Error('Failed to upload to S3');
          }
      } else {
          // Local Storage
        // Calculate relative path from the actual file location to ensure consistency
        const uploadDir = path.join(__dirname, '../../uploads');
        const relativePath = path.relative(uploadDir, file.destination).split(path.sep).join('/');
          
          // Ensure relativePath doesn't start with / if it's empty
          const prefix = relativePath && relativePath !== '.' ? `${relativePath}/` : '';
          
          url = `/uploads/${prefix}${file.filename}`;
      }
      
      const meta = metadataMap[file.originalname] || {};

      const fileData = {
        name: file.originalname,
        size: file.size,
        mimeType: file.mimetype,
        sha256,
        url: url,
        folderId: req.body.folderId || undefined,
        width: meta.width,
        height: meta.height,
        duration: meta.duration
      };

      const savedFile = await mediaService.createFile(tenantId, fileData);
      uploadedFiles.push(savedFile);
    }

    res.status(201).json(uploadedFiles);
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const getPresignedUrl = async (req: Request, res: Response) => {
  try {
    const { filename, contentType } = req.body;
    const { tenantId } = (req as any).user;
    
    const systemSettings = await systemSettingsService.getSystemSettings();
    const settings = systemSettings?.storage as unknown as StorageSettings | undefined;

    if (!settings || settings.provider !== 's3') {
      return res.status(400).json({ message: 'S3 storage is not configured' });
    }

    const s3Client = new S3Client({
      region: settings.region,
      credentials: {
        accessKeyId: settings.accessKeyId || '',
        secretAccessKey: settings.secretAccessKey || '',
      },
      endpoint: settings.endpoint || undefined,
      forcePathStyle: !!settings.endpoint,
    });

    const relativePath = `${tenantId}/${new Date().getFullYear()}/${(new Date().getMonth()+1).toString().padStart(2, '0')}/${new Date().getDate().toString().padStart(2, '0')}`;
    const key = `uploads/${relativePath}/${Date.now()}-${filename}`;

    const command = new PutObjectCommand({
      Bucket: settings.bucket,
      Key: key,
      ContentType: contentType,
    });

    const url = await getSignedUrl(s3Client, command, { expiresIn: 3600 });

    res.json({ 
      uploadUrl: url, 
      key,
      publicUrl: settings.endpoint 
        ? `${settings.endpoint}/${settings.bucket}/${key}`
        : `https://${settings.bucket}.s3.${settings.region}.amazonaws.com/${key}`
    });
  } catch (error: any) {
    console.error('Presigned URL Error:', error);
    res.status(500).json({ message: error.message });
  }
};

export const registerFile = async (req: Request, res: Response) => {
  try {
    const { tenantId } = (req as any).user;
    const { key, filename, size, mimeType, folderId, metadata, sha256: inputSha256 } = req.body;

    const systemSettings = await systemSettingsService.getSystemSettings();
    const settings = systemSettings?.storage as unknown as StorageSettings | undefined;
    const cdnSettings = systemSettings?.cdn as unknown as CdnSettings | undefined;

    let url = '';
    if (cdnSettings?.enabled && cdnSettings?.baseUrl) {
        const baseUrl = cdnSettings.baseUrl.replace(/\/$/, '');
        url = `${baseUrl}/${key}`;
    } else if (settings?.endpoint) {
         url = `${settings.endpoint}/${settings.bucket}/${key}`;
    } else if (settings?.bucket) {
         url = `https://${settings.bucket}.s3.${settings.region}.amazonaws.com/${key}`;
    } else {
        return res.status(400).json({ message: 'Storage configuration missing' });
    }

    let sha256 = normalizeSha256(inputSha256) || normalizeSha256(metadata?.sha256);
    if (!sha256) {
      if (settings?.provider === 's3' && settings.bucket && key) {
        const s3Client = new S3Client({
          region: settings.region,
          credentials: {
            accessKeyId: settings.accessKeyId || '',
            secretAccessKey: settings.secretAccessKey || '',
          },
          endpoint: settings.endpoint || undefined,
          forcePathStyle: !!settings.endpoint,
        });
        sha256 = await computeSha256FromS3Object(s3Client, settings.bucket, key);
      } else {
        sha256 = await computeSha256FromUrl(url);
      }
    }

    const fileData = {
        name: filename,
        size,
        mimeType,
        sha256,
        url,
        folderId: folderId || undefined,
        width: metadata?.width,
        height: metadata?.height,
        duration: metadata?.duration
    };

    const savedFile = await mediaService.createFile(tenantId, fileData);
    res.status(201).json(savedFile);
  } catch (error: any) {
    console.error('Register File Error:', error);
    res.status(400).json({ message: error.message });
  }
};

const normalizeSha256 = (value: unknown): string | undefined => {
  if (typeof value !== 'string') return undefined;
  const normalized = value.trim().toLowerCase();
  return /^[a-f0-9]{64}$/.test(normalized) ? normalized : undefined;
};

const computeSha256FromFile = async (filePath: string): Promise<string> => {
  return await new Promise((resolve, reject) => {
    const hash = crypto.createHash('sha256');
    const stream = fs.createReadStream(filePath);
    stream.on('data', chunk => hash.update(chunk));
    stream.on('end', () => resolve(hash.digest('hex')));
    stream.on('error', reject);
  });
};

const computeSha256FromReadable = async (stream: NodeJS.ReadableStream): Promise<string> => {
  return await new Promise((resolve, reject) => {
    const hash = crypto.createHash('sha256');
    stream.on('data', chunk => hash.update(chunk));
    stream.on('end', () => resolve(hash.digest('hex')));
    stream.on('error', reject);
  });
};

const computeSha256FromS3Object = async (client: S3Client, bucket: string, key: string): Promise<string> => {
  const response = await client.send(new GetObjectCommand({ Bucket: bucket, Key: key }));
  const body = response.Body;
  if (!body || typeof (body as any).on !== 'function') {
    throw new Error('Unable to read uploaded object for checksum');
  }
  return await computeSha256FromReadable(body as NodeJS.ReadableStream);
};

const computeSha256FromUrl = async (url: string, redirectsLeft: number = 3): Promise<string> => {
  return await new Promise((resolve, reject) => {
    const target = new URL(url);
    const client = target.protocol === 'http:' ? http : https;

    const request = client.get(target, response => {
      const status = response.statusCode || 0;
      const location = response.headers.location;

      if (status in { 301: 1, 302: 1, 303: 1, 307: 1, 308: 1 } && location && redirectsLeft > 0) {
        response.resume();
        const nextUrl = new URL(location, target).toString();
        computeSha256FromUrl(nextUrl, redirectsLeft - 1).then(resolve).catch(reject);
        return;
      }

      if (status < 200 || status >= 300) {
        response.resume();
        reject(new Error(`Failed to fetch uploaded file for checksum: HTTP ${status}`));
        return;
      }

      computeSha256FromReadable(response).then(resolve).catch(reject);
    });

    request.on('error', reject);
  });
};

export const createFolder = async (req: Request, res: Response) => {
  try {
    const { tenantId } = (req as any).user;
    const folder = await mediaService.createFolder(tenantId, req.body);
    res.status(201).json(folder);
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const getAllFolders = async (req: Request, res: Response) => {
  try {
    const { tenantId } = (req as any).user;
    const folders = await mediaService.getFolders(tenantId);
    res.json(folders);
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
};

export const getLibrary = async (req: Request, res: Response) => {
  try {
    const { tenantId } = (req as any).user;
    const { folderId, search } = req.query;
    
    const files = await mediaService.getFiles(tenantId, folderId as string, search as string);
    const allFolders = await mediaService.getFolders(tenantId); 
    
    const targetFolderId = (folderId as string) || null;
    const currentFolders = allFolders.filter(f => f.parentId === targetFolderId);

    res.json({ folders: currentFolders, files });
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
};

export const updateFile = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { tenantId } = (req as any).user;
    const file = await mediaService.updateFile(id, tenantId, req.body);
    res.json(file);
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const deleteFile = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { tenantId } = (req as any).user;
    await mediaService.deleteFile(id, tenantId);
    res.json({ message: 'File deleted' });
  } catch (error: any) {
    if (error.code === 'MEDIA_IN_USE') {
        return res.status(409).json({ 
            message: 'File is in use and cannot be deleted', 
            code: 'MEDIA_IN_USE',
            playlists: error.playlists 
        });
    }
    res.status(400).json({ message: error.message });
  }
};

export const updateFolder = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { tenantId } = (req as any).user;
    const folder = await mediaService.updateFolder(id, tenantId, req.body);
    res.json(folder);
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const deleteFolder = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { tenantId } = (req as any).user;
    await mediaService.deleteFolder(id, tenantId);
    res.status(200).json({ message: 'Folder deleted' });
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const bulkDelete = async (req: Request, res: Response) => {
  try {
    const { fileIds = [], folderIds = [] } = req.body;
    const { tenantId } = (req as any).user;
    
    const result = await mediaService.bulkDelete(tenantId, fileIds, folderIds);
    res.status(200).json({ message: 'Operation completed', result });
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};

export const bulkMove = async (req: Request, res: Response) => {
  try {
    const { fileIds = [], folderIds = [], targetFolderId } = req.body;
    const { tenantId } = (req as any).user;
    
    await mediaService.bulkMove(tenantId, fileIds, folderIds, targetFolderId);
    res.status(200).json({ message: 'Items moved' });
  } catch (error: any) {
    res.status(400).json({ message: error.message });
  }
};
